Hunterised ros catkin 0.7.11
hunter-packages/catkin pull request #1
Opened 2018-04-09 22:11 UTC by lsolanka-seebyte

The first installment for ruslo/hunter#1397.

Catkin is a base dependency for each ROS package, but it is not hunter ready. The current patches do the following:
- Do not extract absolute path names from libraries and targets, instead use exported targets
- Properly find_package packages which are listed as dependencies of each catkin package
- Use exported targets when the package is being installed instead of hard coded paths to libraries
  - This requires the dependent packages to define one variable: PROJECT_INSTALLSPACE_LIBRARIES that lists the exported targets. This will be then added to ${catkin_LIBRARIES}, which is a standard way how ROS pulls libraries for linking. This maximizes backwards compatibility with already existing CMakeLists.txt of ROS packages.
- Clean up some other commands which interfere with BUILD_SHARED_LIBS

The final result is that most users will only need to add `hunter_add_package(ros-ros_comm)` (after all packages are added to Hunter) and not touch any other code in their CMakeLists.txt.

Let me know how this looks.

2018-04-10 04:04 UTC, ruslo requested changes

2018-04-10 04:04 UTC, ruslo commented on cmake/platform/windows.cmake
> -  option(BUILD_SHARED_LIBS "Build dynamically-linked binaries" ON)
`option` should work fine, no need to remove it

2018-04-10 04:04 UTC, ruslo commented on cmake/tools/libraries.cmake
> -  option(BUILD_SHARED_LIBS "Build dynamically-linked binaries" ON)
`option` should work fine, no need to remove it

2018-04-10 04:04 UTC, ruslo commented on cmake/test/gtest.cmake
> -find_package(GMock QUIET)
The best approach would be to create minimal patch to simplify updates in future. I think instead of removing the whole block you can just do:
```cmake
if(HUNTER_ENABLED)
  hunter_add_package(...)
  # ....
endif()

if(NOT HUNTER_ENABLED)
  find_package(GMock QUIET)
endif()

if(NOT GMOCK_FOUND AND NOT HUNTER_ENABLED)
  # ...
elseif(NOT HUNTER_ENABLED)
  # ...
endif()
```

Also assuming that this code used for testing and we don't need tests for Hunter may be it make sense to not to touch this block at all and disable testing by some option.

2018-04-10 21:53 UTC, lsolanka-seebyte commented on cmake/test/gtest.cmake
> -find_package(GMock QUIET)
Thanks for this, it's a good idea to add the if() blocks. I have simplified the diff as you're suggesting.

> Also assuming that this code used for testing and we don't need tests for Hunter may be it make sense to not to touch this block at all and disable testing by some option.

The functions catkin_add_gtest() and catkin_add_gmock() are used both for testing the core ROS packages, but also by any other packages, and the usage of these functions is actually quite prevalent. I think it's worth pulling GTest and GMock through Hunter, so that these are available for the downstream Hunterised projects for running the tests without them having to make any patches to the already existing code that use catkin_add_gtest/gmock().

2018-04-10 21:55 UTC, lsolanka-seebyte commented on cmake/test/gtest.cmake
> -find_package(GMock QUIET)
There is a CATKIN_ENABLE_TESTING option which if set to OFF will disable building any tests. This can be put to hunter.cmake for each package.

2018-04-10 21:57 UTC, lsolanka-seebyte commented on cmake/test/gtest.cmake
> +if(GTEST_FOUND AND NOT HUNTER_ENABLED)
I have re-instated this block but only for HUNTER_ENABLED=OFF. I assume this is not necessary when using Hunter - all seems to compile fine without it, but please let me know if this should be unconditional.

2018-04-10 22:14 UTC, lsolanka-seebyte commented on cmake/platform/windows.cmake
> -  option(BUILD_SHARED_LIBS "Build dynamically-linked binaries" ON)
Both platform/windows.cmake and tools/libraries.cmake are included with every catkin package CMakeLists.txt. When I leave this option with default `ON` the system tries to build everything with shared libraries. Perhaps I'm missing something? Is `BUILD_SHARED_LIBS` set to `OFF` by default inside `HunterGate()` or `hunter_add_package()`?

I'll double check tomorrow though and see if something changed since last time I tried to compile with these blocks present.

2018-04-11 08:08 UTC, ruslo commented on cmake/platform/windows.cmake
> -  option(BUILD_SHARED_LIBS "Build dynamically-linked binaries" ON)
> Is BUILD_SHARED_LIBS set to OFF by default inside HunterGate() or hunter_add_package()?

Yes, but it's not really related. `option` is customizable feature, user can always control it from outside. If you use `option` in code you simply declaring default value hence there is no need to remove it:
* https://cgold.readthedocs.io/en/latest/tutorials/variables/cache.html#use-case

2018-04-11 08:09 UTC, ruslo commented on cmake/test/gtest.cmake
> -find_package(GMock QUIET)
> This can be put to hunter.cmake for each package

👍

2018-04-11 08:17 UTC, ruslo requested changes

2018-04-11 08:17 UTC, ruslo commented on cmake/test/gtest.cmake
> +if(GTEST_FOUND AND NOT HUNTER_ENABLED)
It seem this change is not needed.

2018-04-11 08:17 UTC, ruslo commented on cmake/test/gtest.cmake
> +    if(NOT EXISTS "${GTest_LICENSES}")
This code can be removed if you're not really using `GTest_LICENSES` variable.

2018-04-11 08:17 UTC, ruslo commented on cmake/templates/pkgConfig.cmake.in
> +set(depends "@PROJECT_DEPENDENCIES@")
Minimizing patch goal: this code can be moved lower.

2018-04-11 08:17 UTC, ruslo commented on cmake/catkin_package.cmake
> +  set(PROJECT_DEPENDENCIES ${PROJECT_DEPENDS})
Minimizing patch goal: can we just add some code to nullify the effect of `foreach(depend ${PROJECT_DEPENDS})` loop instead of removing it completely?

2018-04-12 00:06 UTC, lsolanka-seebyte commented on cmake/catkin_package.cmake
> +  set(PROJECT_DEPENDENCIES ${PROJECT_DEPENDS})
Done. Thanks for that. I had to add some nullify statements, otherwise absolute paths to libraries would be propagated inside `LINK_INTERFACE_LIBRARIES` of exported targets (see the new diff).

2018-04-12 05:09 UTC, ruslo requested changes

2018-04-12 05:09 UTC, ruslo commented on cmake/platform/windows.cmake
> -  option(BUILD_SHARED_LIBS "Build dynamically-linked binaries" ON)
☝️

2018-04-12 05:09 UTC, ruslo commented on cmake/test/gtest.cmake
> +    if(NOT EXISTS "${GTest_LICENSES}")
☝️

2018-04-12 05:09 UTC, ruslo commented on cmake/tools/libraries.cmake
> -  option(BUILD_SHARED_LIBS "Build dynamically-linked binaries" ON)
☝️

2018-04-12 05:09 UTC, ruslo commented on cmake/test/gtest.cmake
> +if(GTEST_FOUND AND NOT HUNTER_ENABLED)
☝️

2018-04-12 05:09 UTC, ruslo commented on cmake/templates/pkgConfig.cmake.in
> +set(depends "@PROJECT_DEPENDENCIES@")
☝️

2018-04-12 23:10 UTC, lsolanka-seebyte commented on cmake/templates/pkgConfig.cmake.in
> +set(depends "@PROJECT_DEPENDENCIES@")
Ok, I've moved this down and therefore minimized removed lines. However, as a side effect I had to add some extra code to traverse the libraries that are exported by the project (and which will be added to ${catkin_LIBRARIES} of downstream projects). The diff is slightly smaller but not that much.

I'm afraid that's as much as I can do, in order to not break code where a package has a dependency a library that needs to be found using find_library().

2018-04-12 23:28 UTC, lsolanka-seebyte commented on cmake/platform/windows.cmake
> -  option(BUILD_SHARED_LIBS "Build dynamically-linked binaries" ON)
Thanks for the link, I actually didn't know the `option` works as a cached variable.

The issue I have with what you want me to do is that the initial value for `BUILD_SHARED_LIBS` above is set to `ON`, which forces the shared libs. I am not aware where Hunter really sets it to OFF by default because when I try to recompile with the option above (when reverting the patch) all libraries are built as .so - in rospp for instance.

Can you perhaps just confirm that you want to have this option's initial value set to `ON` as in the code above? I'm happy to keep the option but I think it should be set to `OFF`, i.e. no initial value. Otherwise that will force us to include a BUILD_SHARED_LIBS=OFF line to in hunter.cmake in each package that will come?

2018-04-12 23:29 UTC, lsolanka-seebyte commented on cmake/tools/libraries.cmake
> -  option(BUILD_SHARED_LIBS "Build dynamically-linked binaries" ON)
See my reply for the other file.

2018-04-12 23:35 UTC, lsolanka-seebyte commented
I think I have addressed all comments except the `BUILD_SHARED_LIBS` where I just want to get some clarification on the initial value.

For patch minimization: I have provided explanation above for each change that I think is necessary in order to keep consistency with ROS conventions, and especially the usage of find_library in various ROS packages that use catkin.

Let me know if you see some further ways how to minimize the patch or if you have any further comments.

2018-04-12 23:37 UTC, lsolanka-seebyte commented
Also let me know if I missed something.

2018-04-13 21:32 UTC, lsolanka-seebyte commented on cmake/platform/windows.cmake
> -  option(BUILD_SHARED_LIBS "Build dynamically-linked binaries" ON)
> Is BUILD_SHARED_LIBS set to OFF by default inside HunterGate() or hunter_add_package()?
> 
> Yes, but it's not really related. option is customizable feature, user can always control it from outside. If you use option in code you simply declaring default value hence there is no need to remove it:
> 
>     https://cgold.readthedocs.io/en/latest/tutorials/variables/cache.html#use-case
Ok, taking back what I said above. I see how Hunter creates a cache file in which `BUILD_SHARED_LIBS=OFF`. So all dependencies of a parent project will be built as static, unless overridden.

However, if the user decides to have the parent project to remain a catkin_package by having the usual ROS commands (simplified example for `roscpp`):

```
project(roscpp)

hunter_add_package(ros-catkin)
hunter_add_package(ros-roscpp_core)
# more dependencies

find_package(catkin REQUIRED COMPONENTS
  cpp_common message_generation rosconsole roscpp_serialization roscpp_traits
  rosgraph_msgs rostime std_msgs xmlrpcpp
)

catkin_package(
  # INCLUDE_DIRS ...
  # LIBRARIES roscpp ${PTHREAD_LIB}
  # CATKIN_DEPENDS cpp_common message_runtime ...
  # DEPENDS "Boost COMPONENTS chrono filesystem signals system"
)
```

Then this will include `windows.cmake` and `library.cmake` into the parent project, which in turn will build the parent project with shared libs. This would be a bit unexpected for someone who is building with Hunter and expecting the project to have static libs perhaps?

Let me know what you think, I'm happy to go with whatever you think is best but the above happens when I actually build a ROS application and the options are set to initial value ON.

Sorry for a long comment for such a small thing...

2018-04-14 11:25 UTC, ruslo commented on cmake/platform/windows.cmake
> -  option(BUILD_SHARED_LIBS "Build dynamically-linked binaries" ON)
> Then this will include windows.cmake and library.cmake into the parent project, which in turn will build the parent project with shared libs

Will not be a problem if user will do `option(BUILD_SHARED_LIBS "...")` before but I agree that it's pretty surprising behavior, I'm okay with removing it.

2018-04-14 11:26 UTC, merged

2018-04-14 11:26 UTC, ruslo commented
Released: https://github.com/hunter-packages/catkin/releases/tag/v0.7.11-p0